# Config defaults for the chatbot when starting up
debug: false
enable_chatgpt: true
enable_diffusion: false
diffusion_steps: 30
chatgpt_temperature: 0.0
diffusion_cfg_scale: 18
diffusion_width: 448
diffusion_height: 640
diffusion_sampler: Euler a
character_preset: miku
